### PR TITLE
Chore: error handling in getPremiumRedeemVaults

### PR DESCRIPTION
**Pull request by ns212**

### CODE REVIEW

**Review by savudani8 — APPROVED** [review]
You'll need to increase the version in package.json as well

**Review by sander2 — CHANGES_REQUESTED** [review]
It's good not to fatally crash when an error occurs, but I feel like this isn't really addressing the root of the issue - why is `isBelowPremiumThreshold` producing an error in the first place?

**Comment by savudani8** [comment]
@sander2 I think this can be merged since the root problem was in `index`

**Review by sander2 — APPROVED** [review]
Now that the root issue has been identified and fixed, I no longer have any objections here

**Pull request merged**
