### PR TITLE
feat(request-timestamps): potential timestamp implementation for issue?

### PR DESCRIPTION
**Pull request by theodorebugnet**
Will query the parachain twice extra for every issue request!

### CODE REVIEW

**Review by savudani8 — APPROVED** [review]
Up to @nud3l but since the UI will be querying `index` I think it's fine to take the performance hit

**Comment by theodorebugnet** [comment]
I have the opposite opinion, since the UI will be querying index we don't really need the timestamp here, but the lib should still be usable for other people who want to integrate with the parachain. Not every single usecase will need the timestamp, and a mandatory 3x performance hit seems excessive for just one non-critical field.

**Comment by savudani8** [comment]
In this case you can expose a `getTimestampFromBlocknumber()` function using the logic in this PR to let users decide whether/where to call it. A good place to add it could be `src/utils/encoding.ts`

**Comment by nud3l** [comment]
I am in favor of having the timestamp on `issue.request()` but against having it on other calls for the performance penalty reason. However, with a different implementation approach:

If you were to do this accurately, you would go the way of: `request` is using `sendLogged` under the hood. This already awaits the transactions being included and includes the block hash at which the transaction is included. So instead of making another extra call to translate the block height to the hash, you can get away with just a single timestamp call.

But, that will be more or less the same as if you'd just use `Date.now()` on the request API. So I think we should just go with that.

On any list calls, I would not add it automatically due to performance issues. I like Dan's suggestions though to add this API call for getting a timestamp for a block number.

What do you think?

**Pull request closed without merging**
